pollarize/poll_app/urls.py
from django.urls import path
from poll_app import views
from poll_app.views import JSONRandomPoll, JSONPollByPopularity, JSONComments, JSONChildComments, ResultsView, JSONPollResults, VoteView, JSONAddVote

app_name = "poll_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.homepage, name="home"),
    path("about/", views.about, name="about"),
    path("rankings/", views.rankings, name="rankings"),
    path("random-poll/", views.random_poll, name="random"),
    path("create-poll/", views.create, name="create"),
    path("search/", views.search, name="search"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("account/", views.account, name="account"),
    path('register/', views.register, name='register'),
    path("<slug:poll_slug>/vote/", views.vote, name="vote"),
    path("user/<int:user_id>/", views.user, name="user"),
    path("<slug:poll_slug>/results/", ResultsView.as_view(), name="results"),
    path("json/random/", JSONRandomPoll.as_view(), name="json-random"),
    path("json/poll-popular/", JSONPollByPopularity.as_view(), name="json-popularity"),
    path("json/<slug:poll_slug>/comments/", JSONComments.as_view(), name="json-comments"),
    path("json/<int:comment_id>/child-comments/", JSONChildComments.as_view(), name="json-child-comments"),
    path("json/add-comment/", views.add_comment, name="add-comment"),
    path("json/add-comment-vote/", views.add_comment_votes, name="add-vote"),
    path("json/<slug:poll_slug>/results/", JSONPollResults.as_view(), name="json-results"),
    path("json/add-vote/", views.JSONAddVote, name="json-add-vote"),
    path("json/search/", views.JSONSearch, name="json-search"),
    path("json/user/", views.JSONGetCurrentUser, name="json-user"),
    path("json/<int:comment_id>/rating/", views.get_comment_votes, name="json-comment-rating"),
    path("json/delete-comment/", views.JSONDeleteComment, name="json-delete-comment")
    
]

pollarize/pollarize/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from poll_app import views
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,user):
        return reverse('poll_app:register')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register/',MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('', include("poll_app.urls")),] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollarize/poll_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone
from PIL import Image

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    profile_image = models.ImageField(null=True, upload_to='profile_images', blank=True, default="default.png")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        profile_image = Image.open(self.profile_image.path)
        profile_image.save(self.profile_image.path, quality=40, optimize=True)

    def __str__(self):
        return self.user.username



class Poll(models.Model):
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.CharField(max_length=300, null=False)
    poll_slug = models.SlugField(max_length=300, default="")
    answer1 = models.CharField(max_length=200, null=False)
    answer2 = models.CharField(max_length=200, null=False)
    votes1 = models.IntegerField(default=0)
    votes2 = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.question)
        if self.votes1 < 0:
            self.votes1 = 0
        if self.votes2 < 0:
            self.votes2 = 0
        super(Poll, self).save(*args, **kwargs)

    def __str__(self):
        return self.question

class Comment(models.Model):
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    votes = models.IntegerField(default=0)
    parent = models.ForeignKey("self", null=True, related_name="comments", on_delete=models.CASCADE, blank=True)

    def save(self, *args, **kwargs):
        if self.parent == self:
            self.parent = None
        super(Comment, self).save(*args, **kwargs) 
    
    def __str__(self):
        return self.comment

class VotesIn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    option = models.CharField(max_length=100)
    vote_time = models.DateTimeField('date voted', default=timezone.now)


# This is a linker model to only give a user one upvote or downvote
class VotesInComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    old_votes = models.IntegerField(default=0)

pollarize/poll_app/forms.py
from django import forms
from poll_app.models import UserProfile, Poll, Comment
from django.contrib.auth.models import User


class CreatePollForm(forms.ModelForm):
    # user input
    question = forms.CharField(max_length=128, help_text="Please enter the poll question:")
    answer1 = forms.CharField(max_length=5000, help_text="Please enter the first option:")
    answer2 = forms.CharField(max_length=5000, help_text="Please enter the second option:")

    # hidden fields
    votes1 = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    votes2 = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    poll_slug = forms.SlugField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Poll
        fields = ('question', 'answer1', 'answer2')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('profile_image',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password",)

pollarize/poll_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, Http404
from django.views import View
from poll_app.models import Poll, Comment, UserProfile, VotesIn, VotesInComment
from poll_app.forms import CreatePollForm, UserProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.urls import reverse
from django.db.utils import IntegrityError
import random
from django.contrib.auth import authenticate, login, logout
import re

# Create your views here.


# Sort polls by popularity and return sorted list
def popular(polls):
    popular = [(poll, poll.votes1 + poll.votes2) for poll in polls]
    popular = sorted(popular, key=lambda x: x[1], reverse=True)
    return [poll[0] for poll in popular]


# Sort polls by pollarizing (closeness to 50/50 answer rate) and return sorted list
def pollarizing(polls):
    # Calculate and sort by difference of percentage of option 1 with 50% (ascending order)
    pollarizing = [(poll, pollarizing_score(poll)) for poll in popular(polls)]
    pollarizing = sorted(pollarizing, key=lambda x: x[1])
    return [poll[0] for poll in pollarizing]


# Calculate score of each poll for pollarizing
def pollarizing_score(poll):
    total = poll.votes1 + poll.votes2
    if total == 0:
        return 100
    return abs(((poll.votes1 / (total)) * 100) - 50)


# Sort polls by recency and exclude future polls (with publish time after current time)
def recent_polls(polls):
    polls = polls.order_by('-pub_date')
    return list(polls)


# Format votes string on about page depending on number of votes
def votes_string(no_votes):
    if no_votes < 1000:
        return str(no_votes) + " votes"
    # Round to nearest 100 with more than 1,000 votes
    elif no_votes < 1000000:
        return str(round((no_votes / 1000), 1)) + "K votes"
    # Round to nearest 100,000 with more than 1,000,000 votes
    else:
        return str(round((no_votes / 1000000), 1)) + "M votes"



#Empty URL redirects to homepage
def index(request):
    return redirect("poll_app:home")


def homepage(request):
    # Get all polls not from the future
    polls = Poll.objects.filter(pub_date__lt=timezone.now())

    # Get recent polls
    recent = recent_polls(polls)[:3]

    # Get pollarizing and popular polls
    popular_polls = popular(polls)[:3]
    pollarizing_polls = pollarizing(polls)[:3]

    #Populate dictionary
    context_dict = {"recent": recent,
                    "popular": popular_polls,
                    "pollarizing": pollarizing_polls}

    #Create response render
    response = render(request, 'poll_app/index.html', context=context_dict)
    return response


#About page
def about(request):
    return render(request, "poll_app/about.html")


def rankings(request):

    polls = Poll.objects.filter(pub_date__lt=timezone.now())
    # Get recent polls
    recent = recent_polls(polls)[:10]

    # Get pollarizing and popular polls
    popular_polls = popular(polls)[:10]
    pollarizing_polls = pollarizing(polls)

    #Get most pollarizing poll as champion to show separately on page
    champion = pollarizing_polls[0]

    # Remove champion poll from secondary list if there are enough polls to fill space
    if len(pollarizing_polls) > 10:
        pollarizing_polls = pollarizing_polls[1:11]
    else:
        pollarizing_polls = pollarizing_polls[:10]

    #Populate dictionary
    context_dict = {"champion": champion,
                    "recent": recent,
                    "popular": popular_polls,
                    "pollarizing": pollarizing_polls}

    #Create response render
    response = render(request, 'poll_app/rankings.html', context=context_dict)
    return response

def random_poll(request):
    # Get a random poll
    polls = Poll.objects.filter(pub_date__lt=timezone.now())
    the_poll = random.choice(polls)
    the_slug = the_poll.poll_slug

    return redirect("poll_app:vote", poll_slug=the_slug)

@login_required
def create(request):
    #Initialise dictionary, form and user
    context_dict = {}
    form = CreatePollForm()
    user = request.user

    if request.method == 'POST':
        #Get form information and create poll object
        form = CreatePollForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.submitter = user
            obj.pub_date = timezone.now()
            obj.poll_slug = slugify(obj.question)
            obj.save()
            #Redirect to vote page
            return redirect(reverse("poll_app:vote", kwargs={'poll_slug': obj.poll_slug}))
        else:
            print(form.errors)

    #If not POST request, show create form
    context_dict['form'] = form
    return render(request, "poll_app/create.html", context=context_dict)

def search(request):

    #Define list of stopwords not considered by the search
    stopwords = ["a", "and", "by", "be", "to", "the", "of", "that", "i", "not", "for", "on", "as", "do", "at", "but"]
    #Maximum number of polls and accounts in results
    poll_results_limit = 10
    account_results_limit = 10

    if request.method == 'POST':
        #Get search input
        query = request.POST.get('query')
        #If empty, show results page
        if len(query) == 0:
            return redirect(reverse("poll_app:rankings"))

        #If query is exact match for a poll, go to polls vote page
        try:
            poll = Poll.objects.get(question=query)
            if (poll.pub_date > timezone.now()):
                raise Http404("Can't access poll")
            return redirect(reverse("poll_app:vote", kwargs={'poll_slug': poll.poll_slug}))

        except Poll.DoesNotExist:
            #Get all polls and accounts
            polls = Poll.objects.filter(pub_date__lt=timezone.now())
            polls = popular(polls)
            users = UserProfile.objects.all()

            #Initialise lists
            found_polls = []
            found_users = []

            #Split search into individual words
            query_args = query.lower().split(" ")
            for arg in query_args:
                #Search all non-stopwords
                if not arg in stopwords:
                    #Don't loop if maximum number of polls already found
                    if len(found_polls) <= poll_results_limit:
                        for poll in polls:
                            #If we find a new match, add it to the list
                            if not (poll in found_polls) and re.search(arg, poll.question, re.IGNORECASE):
                                found_polls.append(poll)
                                #Break if we've found enough polls
                                if len(found_polls) >= poll_results_limit:
                                    break

                    # Don't loop if maximum number of accounts already found
                    if len(found_users) <= account_results_limit:
                        for acc in users:
                            # If we find a new match, add it to the list
                            if not (acc in found_users) and re.search(arg, acc.user.username, re.IGNORECASE):
                                found_users.append(acc)
                                # Break if we've found enough polls
                                if len(found_users) >= account_results_limit:
                                    break
            #Build dictionary and return search page
            context_dict = {
                "query": query,
                "polls": found_polls,
                "users": found_users
            }
            return render(request, "poll_app/search.html", context=context_dict)

    #Return empty search page if there is no post
    return render(request, "poll_app/search.html")

def register(request):
    #Initialise form
    form = UserProfileForm()

    if request.method == 'POST':
        print(request.POST)
        print(request.FILES)
        #Create new user from form values
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            try:
                user_profile.user = request.user
                user_profile.save()
            except IntegrityError:
                the_file = request.FILES["profile_image"]
                old_profile = UserProfile.objects.get(user=request.user)
                old_profile.profile_image = the_file
                old_profile.save()

            return redirect(reverse('poll_app:home'))
        else:
            print(form.errors)
    else:
        #If user has no profile picture, set it to the default
        user = request.user
        if user.is_authenticated:
            profile = UserProfile.objects.get_or_create(user=request.user)[0]
            if not profile.profile_image:
                profile.profile_image = 'default.png'
                profile.save()

    context_dict = {'form': form}
    return render(request, 'poll_app/registration.html', context_dict)

def login_view(request, error=None):
    if request.method == 'POST':
        #Get form data
        username = request.POST.get('username')
        password = request.POST.get('password')
        #Check credentials
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('poll_app:home'))
            else:
                #Re-render login page with error if account disabled
                return render(request, 'poll_app/login.html',
                context={"error": "Your Pollarize account is disabled."})
        else:
            # Re-render login page with error if password doesn't match

pollarize/templates/poll_app/about.html
{% extends 'poll_app/base.html'%}
{% load staticfiles %}
<!--Fill in page title and load css/javascript-->
{% block head_block %}
       <link rel="stylesheet" href="{% static 'css/about.css' %}">
       <title>Pollarize - About us</title>
{% endblock %}

{% block body_block %}
    <img id="main_logo" src="{% static 'img/logo_colour.png' %}" alt="Pollarize Logo"></img>
        <h1 id="title" class="about_title">About us</h1>
        <div class="divider"></div>
        <h2 class="paragraph_text">Want to know what everyone thinks about the big issues? Have a burning question you need to ask the world? Need somewhere to copy and paste that 3 page essay you wrote about how Goku would absolutely destroy Superman? From the <em>serious debate topics</em> to the <em>silliest arguments</em> - for the college students, the marketing experts, and the hardcore DC Comics fans - there's a <em>poll for everyone!</em></h2>
        <div class="action_buttons">
            <form action="{% url 'poll_app:random' %}">
                <button type="submit" class="orange_button">Try a random poll!</button>
            </form>
        </div>
        <h2 class="paragraph_text">If you really can't find what you're looking for, you can always <em>create your own poll!</em></h2>
        <div class="action_buttons">
            <form action="{% url 'poll_app:create' %}">
                <button type="submit" class="grey_button">Make a poll!</button>
            </form>
        </div>

         <h2 class="paragraph_text">The polls on our website are ranked by how <em>"Pollarizing"</em> they are (how close to a 50/50 answer rate they have) and the top polls are shown at the centre of our <em><a href="index.html">Homepage!</a></em></h2>
        <div class="action_buttons">
            <form action="{% url 'poll_app:rankings' %}">
                <button type="submit" class="orange_button">Check out our rankings!</button>
            </form>
        </div>

        <div class="orange_box">
            <h2 id="orange_box_header">With a <em>Pollarize</em> account, you can: </h2>
                <ul>
                    <li>Vote in one of our many <a href="{% url 'poll_app:random' %}">polls!</a></li>
                    <li>Leave a comment after voting</li>
                    <li><a href="{% url 'poll_app:create' %}">Create your own polls</a> and top the <a href="{% url 'poll_app:rankings' %}">rankings!</a></li>
                </ul>
                <br />
                <div class="action_buttons">
                    <form action="{% url 'poll_app:login' %}">
                        <button type="submit" class="grey_button" id="login_button">Log In / Sign Up</button>
                    </form>
                </div>
        </div>
{% endblock %}

pollarize/templates/poll_app/account.html
{% extends 'poll_app/base.html'%}
{% load staticfiles %}

{% block head_block %}
       <title>Pollarize - Account</title>
       <script type="text/javascript" src="{% static 'js/account.js' %}"></script>
       <script type="text/javascript" src="{% static 'js/account_delete.js' %}"></script>
       <link rel="stylesheet" href="{% static 'css/account.css' %}">

{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
       {% if error %}
              <div class="error_box">{{ error }}</div>
       {% endif %}

<div class="container">
       <div class="grid-item" id="item1">
              <img src="{{ profile.profile_image.url }}" id="profile_img" class="profile"></img>
              <div class="overlay">
                     <div id="center-image">
                            <a href="{% url 'poll_app:register' %}" id="change-image-link">
                                   Change Profile Image
                            </a>
                     </div>
              </div>
       </div>
       <div class="grid-item" id="item2">
              <h1>Stats</h1>
              <ul>
                     <li>Username: {{ user.username }}</li>
                     {% if user.email %}
                     <li>Email: {{ user.email }}</li>
                     {% endif %}
                     <li>Polls Submitted: {{ polls }}</li>
                     <li>You have voted in {{ votes_in }} polls</li>
                     <li>Comments: {{ comments }}</li>
              </ul>
       </div>

</div>
       <div class="action_buttons">
              <button class="red_button" id="delete_button">Delete account</button>
       </div>

       <div id="account_delete_block">
              <h1>Please enter your password to delete your account: </h1>
              <form id="account_delete_form" method="post" action="{% url 'poll_app:account' %}">
                     {% csrf_token %}
                     <input type="password" name="password" value="" size="50" /> <br />
                     <div class="action_buttons">
                            <button type="submit" class = "red_button" id="confirm_button">Confirm deletion</button>
                     </div>
              </form>
       </div>
{% endif %}
{% endblock %}

pollarize/templates/poll_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    {% csrf_token %}
    <!-- Set metadata -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Load main stylesheet -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <!-- JavaScript files -->
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/account_drop_down.js' %}"></script>
    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700;800&display=swap" rel="stylesheet">
    <!-- Get head block -->

    <!-- CSS for the search block-->
    <link rel="stylesheet" href="{% static 'css/search.css' %}"/>
    {% block head_block %}
    {% endblock %}
</head>

<body>
    <!-- Account drop down menu -->
    <div id="account_drop_down">
        <h1><a href="{% url 'poll_app:account' %}">Account</a></h1>
        <h1><a href="{% url 'poll_app:logout' %}">Log out</a></h1>
    </div>

    <!-- Create navbar -->
    <div class="navbar">
        <!-- Homepage logo (and smaller logo for smaller resolutions) -->
        <a href="{% url 'poll_app:home' %}" id="logo_container" title="Homepage"><img id="navbar_logo" src="{% static 'img/logo_text_small.png' %}" alt="Homepage" height="30px"></a>
        <a href="{% url 'poll_app:home' %}" id="small_logo_container" title="Homepage"><img id="navbar_logo_small" src="{% static 'img/logo_mono.png' %}" alt="Homepage" height="35px"></a>
        <!-- About text (and logo for smaller resolutions) -->
        <a href="{% url 'poll_app:about' %}" class="navbar_text">About</a>
        <a href="{% url 'poll_app:about' %}" id="about_icon"><img src="{% static 'img/about_icon.png' %}" alt="About" height="25px" width="25px" title="About"></a>
        <!-- Rankings text (and logo for smaller resolutions) -->
        <a href="{% url 'poll_app:rankings' %}" class="navbar_text">Rankings</a>
        <a href="{% url 'poll_app:rankings' %}" id="ranking_icon" title="Rankings"><img src="{% static 'img/ranking_icon.png' %}" alt="Rankings" height="25px" width="25px"></a>
        <!-- Random poll text (and logo for smaller resolutions) -->
        <a href="{% url 'poll_app:random' %}" class="navbar_text">Random Poll</a>
        <a href="{% url 'poll_app:random' %}" id="random_icon" title="Random Poll"><img src="{% static 'img/random_icon.png' %}" alt="Random Poll" height="25px" width="25px"></a>
        <!-- Create poll text (and logo for smaller resolutions) -->
        <a href="{% url 'poll_app:create' %}" class="navbar_text">Create Poll</a>
        <a href="{% url 'poll_app:create' %}" id="create_icon" title="Create Poll"><img src="{% static 'img/create_icon.png' %}" alt="Create Poll" height="25px" width="25px"></a>
        <!-- Search bar and button -->
        <div id="search_container">
        <form class="search_form" method="post" action="{% url 'poll_app:search' %}">
            {% csrf_token %}
            <input type="text" id="searchbar" list="search-results" placeholder="Search for polls..." name="query">
            <button type="submit"><img src="{% static 'img/search_icon.png' %}" id="search_icon" alt="Search" width="20px" height="20px"></i></button>
          </form>
          <datalist id="search-results"></dataset>
        </div>

        <!-- Account picture or login option if no account is logged in -->
        {% if user.is_authenticated %}
            <a id="navbar_account"><img id="profile_icon" src="{{ user.user_profile.profile_image.url }}" alt="Profile" height="35px" width="35px"></img> </a>
        {% else %}
            <a id="navbar_login" href="{% url 'poll_app:login' %}">Log In</a>
            <a id="navbar_register" href="{% url 'registration_register' %}">Register</a>
        {% endif %}

    </div>

    
    
      <div class="main">
        
        {% block body_block %}
        {% endblock %}
      </div>
    <!-- Back to top button -->
      <div id="back-to-top-div">
        <script src="{% static 'js/top_scroll.js' %}"></script>
        <img class="back-to-top" id="back-to-top-img" src="{% static 'img/top_arrow.png' %}" height="50px"></img>
      </div>

</body>

</html>

pollarize/templates/poll_app/index.html
{% extends 'poll_app/base.html'%}
{% load staticfiles %}

{% block head_block %}
       <script src="{% static 'js/populate_boxes.js' %}"></script>
       <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
       <title>Pollarize - Ranking the rankings</title>
{% endblock %}

{% block body_block %}
          <div id="top_text">
            <h1>Have a say in one of our many polls, or create your own and <br />
            compete to become the <em>pollarize champion!</em></h1>
            <div class="action_buttons">
                <form action="{% url 'poll_app:random' %}">
                    <button type="submit" class="orange_button">Random poll</button>
                </form>
                <form action="{% url 'poll_app:create' %}">
                    <button type="submit" class="grey_button">Create poll</button>
                </form>
            </div>
        </div>

            <div class="orange_box">
                {% if recent %}
                <div id="vote_boxes_container">
                    <div id="left">
                        <h1>Popular</h1>
                        {% for poll in popular %}
                            {% include "poll_app/poll_box.html" with poll=poll %}
                        {% endfor %}
                    </div>

                    <div id="middle">
                        <h1>Pollarizing</h1>
                        {% for poll in pollarizing %}
                            {% include "poll_app/poll_box.html" with poll=poll %}
                        {% endfor %}
                    </div>

                    <div id="right">
                        <h1>Recent</h1>
                        {% for poll in recent %}
                            {% include "poll_app/poll_box.html" with poll=poll %}
                        {% endfor %}
                    </div>

                </div>
                {% endif %}
                <div class="about_section">
                    <h1>Want to find out more?</h1>
                    <div class="action_buttons">
                        <form action="{% url 'poll_app:about' %}">
                            <button type="submit" class="grey_button" id="about_button">About us</button>
                        </form>
                    </div>
                </div>
            </div>
{% endblock %}

pollarize/templates/poll_app/login.html
{% extends 'poll_app/base.html'%}
{% load staticfiles %}

{% block head_block %}
       <link rel="stylesheet" href="{% static 'css/login.css' %}">
       <title>Pollarize - Login</title>
{% endblock %}

{% block body_block %}
       {% if error %}
              <div class="error_box">{{ error }}</div>
       {% endif %}
       <h1 id="title">Welcome back to <em>Pollarize!</em></h1>
       <div class="divider"></div>
       <div id="login_box">
              <form id="login_form" method="post" action="{% url 'poll_app:login' %}">
                     {% csrf_token %}
                     <h3>Username:</h3> <input type="text" name="username" value="" size="50" /> <br />
                     <h3>Password:</h3> <input type="password" name="password" value="" size="50" /> <br />
                     <div class="action_buttons">
                            <button type="submit" class = "grey_button" id="login_button">Log in</button>
                     </div>

              </form>
       </div>
       <h2>Don't have an account yet?</h2>
       <div class="action_buttons">
              <form action="{% url 'registration_register' %}">
                     <button type="submit" class="orange_button" id="register_button">Create an account</button>
              </form>
       </div>
{% endblock %}

pollarize/templates/poll_app/logout.html
{% extends 'poll_app/base.html' %} 
{% load staticfiles %} 

{% block head_block %} 
<title>Pollarize - Logout</title> 
{% endblock %} 

{% block body_block %} 
<h1>This is the logout view</h1>
{% endblock %}

pollarize/templates/poll_app/search.html
{% extends 'poll_app/base.html'%}
{% load staticfiles %}

{% block head_block %}
       <script src="{% static 'js/populate_boxes.js' %}"></script>
       <link rel="stylesheet" href="{% static 'css/search_page.css' %}"/>

       <title>Pollarize - Search</title>
{% endblock %}

{% block body_block %}
{% if not polls and not users %}
       <h1>No results for <em>"{{ query }}"</em></h1>
       <h2>Try searching something else: </h2>
{% endif %}

<!--Search bar-->
<div id="search_page_container">
       <form class="search_form page_search_form" method="post" action="{% url 'poll_app:search' %}">
            {% csrf_token %}
            <input type="text" id="page_searchbar" list="search-results" placeholder="Search for polls..." name="query">
            <button type="submit"><img src="{% static 'img/search_icon.png' %}" id="search_icon" alt="Search" width="20px" height="20px"></i></button>
       </form>
          <datalist id="page-search-results"></dataset>
</div>


{% if polls or users %}
<h1 id="title">Results for <em>"{{ query }}":</em></h1>
<div class="divider"></div>
{% endif %}

       {% if polls %}
              <h2 class="section_title">Polls:</h2>
              {% for poll in polls %}
                     {% include "poll_app/centre_box.html" with poll=poll %}
              {% endfor %}

       {% endif %}

       {% if users %}
              <h2 class="section_title">Users:</h2>
       {% for user in users %}
<div class = "centre_poll_box" id="user_{{ user }}">
    <img src="{{ user.profile_image.url }}" id="profile_img" height="150px"></img>
    <h1><a href="{% url 'poll_app:user' user.id %}">{{ user }}</a></h1>
</div>
       {% endfor %}
       {% endif %}


{% endblock %}